import { Menu } from '@types';

export const menuList: Menu[] = [
  {
    id: '5',
    krName: '아메리카노',
    enName: 'Americano',
    price: 3000,
    desc: '[진함 고소함] 견과류 풍미와 초콜릿처럼 달콤 쌉싸름한 맛이 밸런스 있게 어우러진 균형잡힌 바디감의 커피  ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_aa618eecef95.png',
    categoryId: '0',
  },
  {
    id: '473',
    krName: '시그니처아메리카노',
    enName: 'Signature Americano',
    price: 3200,
    desc: '[화사한 산미] 은은한 과일향의 부담없는 산미와 카라멜의 단맛, 견과의 풍미가 어우러진 감칠맛이  가득한 커피 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_e1983f793ad7.png',
    categoryId: '0',
  },
  {
    id: '539',
    krName: '헥사메리카노',
    enName: 'Hexamericano',
    price: 3500,
    desc: '[4 shot] 6가지 원두를 블렌딩해 만든, 고소 & 상큼한 풍미의 밸러스가 좋은 4shot의 진한 아메리카노',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_350a5a914a51.png',
    categoryId: '0',
  },
  {
    id: '540',
    krName: '제로슈가아메리카노',
    enName: 'Zero Sugar Americano',
    price: 3500,
    desc: '스테비아가 첨가 된 아메리카노로 칼로리 걱정없이, 당 걱정없는 달콤한 아메리카노',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c02fe040d0ad.png',
    categoryId: '0',
  },
  {
    id: '7',
    krName: '헤이즐넛아메리카노',
    enName: 'Hazelnut Americano',
    price: 3500,
    desc: '고소한 아메리카노에 헤이즐넛을 더해 달콤 고소한 풍미를 살린 아메리카노',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_dd9bbc721a56.png',
    categoryId: '0',
  },
  {
    id: '12',
    krName: '카페모카',
    enName: 'Cafe Mocha',
    price: 4800,
    desc: '초콜릿 풍미에 에스프레소를 더한 달콤하면서도 쌉싸름한 맛의  커피 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1418e586eccc.png',
    categoryId: '0',
  },
  {
    id: '472',
    krName: '바나리카노',
    enName: 'Banaricano',
    price: 4500,
    desc: '[32oz / 4Shots] 고소한 견과류 풍미와 균형잡힌 바디감을 자랑하는 바나프레소 대표 아메리카노의 대용량 버전!!',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7322c5cfdde8.png',
    categoryId: '0',
  },
  {
    id: '316',
    krName: '허니아메리카노',
    enName: 'Honey Americano',
    price: 3500,
    desc: '진한 아메리카노에 부드럽고 은은한 꿀을 더했다. 숙취해소에 GOOD! 바나프레소 스테디셀러~',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_b42c5ce307da.png',
    categoryId: '0',
  },
  {
    id: '9',
    krName: '카페라떼',
    enName: 'Cafe Latte',
    price: 3800,
    desc: '고소한 우유에 진한 에스프레소를 넣어 부드럽게 즐기는 커피 (두유로 변경가능해요.)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0a2935abe540.png',
    categoryId: '0',
  },
  {
    id: '11',
    krName: '바닐라라떼',
    enName: 'Vanilla Latte',
    price: 4300,
    desc: '마다가스카르산 바닐라빈이 들어가 바닐라 맛과 향이 더욱 깊고 풍부해진 바닐라 라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_cd25547832ba.png',
    categoryId: '0',
  },
  {
    id: '57',
    krName: '크리미라떼',
    enName: 'Creamy Latte',
    price: 4300,
    desc: '부드럽고 달콤한 크림을 더해 깊은 풍미를 느낄 수 있는, 바나프레소만의 스페셜 커피이자 스테디셀러',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_85b82596d833.png',
    categoryId: '0',
  },
  {
    id: '376',
    krName: '연유라떼',
    enName: 'Condensed Milk Cafe Latte',
    price: 4800,
    desc: '달콤한 연유 & 고소한 카페라떼의 조합. 부드러운 단맛이 매력적인 커피',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1c83ee862db7.png',
    categoryId: '0',
  },
  {
    id: '418',
    krName: '밀크카라멜마키아또',
    enName: 'Milk Caramel Macchiato ',
    price: 4800,
    desc: '은은하게 버터풍미가 도는 밀크카라멜  + 진한에스프레소 + 고소한 우유의 앙상블이 매력적인, 달콤한 카라멜 커피 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6c4dc6cd3999.png',
    categoryId: '0',
  },
  {
    id: '407',
    krName: '피스타치오카페라떼',
    enName: 'Pistachio Cafe Latte',
    price: 4800,
    desc: '고소한 피스타치오 풍미와 진한 에스프레소 맛이 조화롭게 어우러져 예쁜 비주얼과 깊은 풍미를 뽐내는 커피음료',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a739698cd38a.png',
    categoryId: '0',
  },
  {
    id: '416',
    krName: '시나몬라떼',
    enName: 'Cinnamon Latte',
    price: 4800,
    desc: '고소한 우유에 진한 에스프레소를 넣어 만든 카페라떼에, 은은한 시나몬향을 더했다. ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0b5cb986f1f7.png',
    categoryId: '0',
  },
  {
    id: '51',
    krName: '에스프레소',
    enName: 'Espresso',
    price: 3000,
    desc: '4가지 원두(브라질, 콜롬비아, 탄자니아, 라오스)를 블렌딩해 진하게 추출한 깊은 풍미의 커피',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/Espresso.png',
    categoryId: '0',
  },
  {
    id: '14',
    krName: '콜드브루',
    enName: 'Cold Brew',
    price: 3800,
    desc: '저온에서 천천히 우려내 더욱 깔끔한 맛을 자랑하는, 바나프레소 콜드브루',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_15fc4e24e77c.png',
    categoryId: '0',
  },
  {
    id: '492',
    krName: '시그니처콜드브루',
    enName: 'Signature Cold Brew',
    price: 4000,
    desc: '바나프레소 시그니처원두를 천천히 우려낸 베리류 과일의 산미와 달콤한 카라멜 단맛의 콜드브루',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_23079ef56016.png',
    categoryId: '0',
  },
  {
    id: '389',
    krName: '바닐라 콜드브루',
    enName: 'Vanilla Cold Brew',
    price: 4500,
    desc: '고소하고 깔끔한 바나프레소 콜드브루에 달콤한 풍미의 바닐라를 더해 만든 부드러운 콜드브루 커피',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_5889a996fe45.png',
    categoryId: '0',
  },
  {
    id: '390',
    krName: '돌체 콜드브루',
    enName: 'Dolce Cold Brew',
    price: 5000,
    desc: '깔끔한 맛의 바나프레소 콜드브루에 달콤한 연유를 더해 부드러운 단맛을 이끌어낸 커피',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2cb207acf5d8.png',
    categoryId: '0',
  },
  {
    id: '296',
    krName: '디카페인 아메리카노',
    enName: 'DECAF Americano',
    price: 3300,
    desc: '스위스 워터 프로세스 방식으로 카페인을 제거한, 콜롬비아 싱글오리진 디카페인 아메리카노. 균형잡힌 산미와 고소한 맛이 특징!',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_496789e1f269.png',
    categoryId: '0',
  },
  {
    id: '541',
    krName: '디카페인 제로슈가아메리카노',
    enName: 'DECAF Zero Sugar Americano',
    price: 3800,
    desc: '스테비아가 첨가 된 디카페인 아메리카노로 칼로리, 당, 카페인 걱정없는 달콤한 디카페인 아메리카노',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a199cc6f53d3.png',
    categoryId: '0',
  },
  {
    id: '542',
    krName: '디카페인 헤이즐넛아메리카노',
    enName: 'DECAF Hazelnut Americano',
    price: 3800,
    desc: '디카페인 아메리카노에 헤이즐넛을 더해 달콤 고소한 풍미를 살린 디커페인 헤이즐넛아메리카노',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2b950f0840c4.png',
    categoryId: '0',
  },
  {
    id: '301',
    krName: '디카페인 카페모카',
    enName: 'DECAF Cafe Mocha',
    price: 5100,
    desc: '초콜릿 풍미에 에스프레소를 더한 달콤하면서도 쌉싸름한 맛의  커피 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a97cd1361d31.png',
    categoryId: '0',
  },
  {
    id: '518',
    krName: '디카페인 바나리카노',
    enName: 'DECAF Banaricano',
    price: 5100,
    desc: '[32oz / 4shot] 스위스 워터 프로세스 방식으로 카페인을 제거한 바나프레소 디카페인 아메리카노의 대용량 버전',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_81a187b11db2.png',
    categoryId: '0',
  },
  {
    id: '519',
    krName: '디카페인 허니아메리카노',
    enName: 'DACAF Honey Americano',
    price: 3800,
    desc: '디카페인 아메리카노에 꿀을 더해 맛과 향이 부드럽고 숙취해소에 좋은 커피',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6d19857e14bd.png',
    categoryId: '0',
  },
  {
    id: '298',
    krName: '디카페인 카페라떼',
    enName: 'DECAF Cafe Latte',
    price: 4100,
    desc: '부드럽고 고소한 우유 풍미가 살아있는 디카페인 카페라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c4a18dc093ff.png',
    categoryId: '0',
  },
  {
    id: '299',
    krName: '디카페인 바닐라라떼',
    enName: 'DECAF Vanilla Latte',
    price: 4600,
    desc: '마다가스카르산 바닐라빈 풍미로 맛을 더한 디카페인 바닐라라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a88936e8a744.png',
    categoryId: '0',
  },
  {
    id: '300',
    krName: '디카페인 크리미라떼',
    enName: 'DECAF Creamy Latte',
    price: 4600,
    desc: '부드럽고 달콤한 크림을 더해 깊은 풍미를 느낄 수 있는, 디카페인 버전 크리미 라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_14fb5394337e.png',
    categoryId: '0',
  },
  {
    id: '377',
    krName: '디카페인 연유라떼',
    enName: 'DECAF Condensed Milk Cafe Latte',
    price: 5100,
    desc: '부드러운 단맛을 가진, 달콤한 연유를 넣은 디카페인 카페라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8348da91cb85.png',
    categoryId: '0',
  },
  {
    id: '408',
    krName: '디카페인 피스타치오카페라떼',
    enName: 'DECAF Pistachio Cafe Latte',
    price: 5100,
    desc: '고소한 피스타치오를 넣은 라떼에 디카페인 에스프레소를 더한 예쁜 커피 음료',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_479e984bf49a.png',
    categoryId: '0',
  },
  {
    id: '303',
    krName: '디카페인 에스프레소',
    enName: 'DECAF Espresso',
    price: 3300,
    desc: '디카페인 콜롬비아 원두로 추출한, 과일 풍미와 균형 잡힌 산미, 고소한 맛이 특징인 디카페인 싱글오리진 에스프레소',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_357aef1d4472.png',
    categoryId: '0',
  },
  {
    id: '417',
    krName: '디카페인 시나몬라떼',
    enName: 'DECAF Cinnamon Latte',
    price: 5100,
    desc: '시나몬의 풍부한 향과 에스프레소, 부드러운 우유가 어우러진 디카페인 커피 메뉴',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_44c34466f721.png',
    categoryId: '0',
  },
  {
    id: '419',
    krName: '디카페인 밀크카라멜마키아또 ',
    enName: 'DECAF Milk Caramel Macchiato',
    price: 5100,
    desc: '은은하게 버터풍미가 도는 밀크카라멜  + 진한에스프레소 + 고소한 우유의 앙상블이 매력적인, 달콤한 카라멜 커피 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d5eb7d0cf01c.png',
    categoryId: '0',
  },
  {
    id: '16',
    krName: '얼그레이밀크티',
    enName: 'EarlGrey Milk Tea',
    price: 4300,
    desc: '향긋한 얼그레이 홍차와 부드러운 우유의 하모니가 돋보이는 클래식한 맛의 밀크티',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0c08e273cd8b.png',
    categoryId: '1',
  },
  {
    id: '321',
    krName: '얼그레이버블티',
    enName: 'Earl Grey Bubble Tea',
    price: 4800,
    desc: '향긋한 얼그레이 밀크티에 쫀득한 타피오카 펄을 더해 식감을 UP시킨 버블 밀크티',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_148da6d88b38.png',
    categoryId: '1',
  },
  {
    id: '246',
    krName: '흑당밀크티',
    enName: 'Black sugar Milk tea',
    price: 4300,
    desc: '달콤한 흑당시럽에 고소한 우유를 더해 만든 달콤한 흑당밀크티',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_57320507b3f8.png',
    categoryId: '1',
  },
  {
    id: '244',
    krName: '흑당버블티',
    enName: 'Black sugar Bubble Tea',
    price: 4800,
    desc: '흑당시럽+쫀득한 타피오카 펄+고소한 우유의 환상적인 조합. 비주얼부터 식감, 극강의 달콤함까지 모두 잡았다. 달콤한 흑당버블티',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8bdbff00aa9b.png',
    categoryId: '1',
  },
  {
    id: '535',
    krName: '딸기크리미라떼',
    enName: 'Strawberry Creamy Latte',
    price: 5000,
    desc: '크리미한 우유에 딸기를 듬뿍 담아 새콤달콤한 맛과 부드러운 풍미가 조화로운  딸기크리미라떼 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1a7763176701.png',
    categoryId: '1',
  },
  {
    id: '343',
    krName: '토피넛라떼',
    enName: 'Toffee Nut Latte',
    price: 4300,
    desc: "고소한 견과류를 넣어만든 부드러운 라떼 위에 서양식 달고나 '아몬드 브리틀' 올린 달콤고소한 라떼",
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7b8ed53d7eea.png',
    categoryId: '1',
  },
  {
    id: '273',
    krName: '달고나라떼',
    enName: 'Dalgona Latte',
    price: 4300,
    desc: '달콤바삭, 어린시절 학교앞 풍경이 솔솔 떠오르는 추억의 달고나 토핑이 듬뿍 올려진 달콤한 라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ef5e35662c02.png',
    categoryId: '1',
  },
  {
    id: '19',
    krName: '리얼바닐라빈',
    enName: 'Real Vanilla Bean',
    price: 4000,
    desc: '마다가스카르산 바닐라빈 풍미가 한가득! 바닐라와 우유만을 더해 만든, 커피가 들어있지 않은 순수 바닐라라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_40bd5666a9ce.png',
    categoryId: '1',
  },
  {
    id: '18',
    krName: '리얼초코',
    enName: 'Real Choco',
    price: 4000,
    desc: '진한 초콜릿의 풍부한 맛과 향이 그대로 살아있는 제대로된 초코라떼. 바나프레소의 변치않는 스테디셀러',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_3becda51fb3a.png',
    categoryId: '1',
  },
  {
    id: '20',
    krName: '오트밀라떼',
    enName: 'Oatmeal Latte',
    price: 4000,
    desc: '배고플 때 먹으면 포만감 제대로! 건강한 재료 오트밀과 우유를 섞어 만든 고소하고 맛있는 곡물라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_34d763b1820d.png',
    categoryId: '1',
  },
  {
    id: '22',
    krName: '녹차라떼',
    enName: 'Green Tea Latte',
    price: 4300,
    desc: '쌉싸름한 녹차에 부드러운 우유를 섞고 달콤함을 추가해 밸런스를 잡았다. 맛있는 녹차라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ef2fc5c870b5.png',
    categoryId: '1',
  },
  {
    id: '406',
    krName: '피스타치오라떼',
    enName: 'Pistachio Latte',
    price: 4300,
    desc: '예쁜 비주얼과 고소한 맛이 모두 일품! 피스타치오 풍미를 제대로 느낄 수 있는 피스타치오 라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_015748897080.png',
    categoryId: '1',
  },
  {
    id: '23',
    krName: '딸기라떼',
    enName: 'Strawberry Latte',
    price: 4500,
    desc: '상큼한 딸기와 부드러운 우유에 달콤함을 한 스푼 첨가한, 모두가 좋아할 그 맛! 상콤달콤 딸기라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d505c50ed17e.png',
    categoryId: '1',
  },
  {
    id: '313',
    krName: '홍시라떼',
    enName: 'Ripe Persimmon Latte',
    price: 4500,
    desc: '달콤한 홍시와 우유가 만났다. 은은한 단맛이 매력적인 홍시라떼',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_533c9e27ad61.png',
    categoryId: '1',
  },
  {
    id: '72',
    krName: '청포도생과일쥬스',
    enName: 'Greengrape fresh Juice',
    price: 5000,
    desc: '신선한 청포도를 그대로 갈아 만들어 상큼한 맛을 느낄 수 있는 생과일 쥬스',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_e69a0566514c.png',
    categoryId: '2',
  },
  {
    id: '154',
    krName: '토마토생과일쥬스',
    enName: 'Tomato Fresh Juice',
    price: 5000,
    desc: '국내산 붉은 생토마토를 그대로 갈아 만든 생과일 쥬스',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ac1183dd4677.png',
    categoryId: '2',
  },
  {
    id: '74',
    krName: '딸기쥬스',
    enName: 'Strawberry Juice',
    price: 4500,
    desc: '언제먹어도 맛있는, 새콤달콤 딸기쥬스',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6dd7097c7bc4.png',
    categoryId: '2',
  },
  {
    id: '75',
    krName: '망고쥬스',
    enName: 'Mango Juice',
    price: 4500,
    desc: '달달한 망고의 맛과 향이 입안가득 퍼지는 망고쥬스',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_571b16e834cd.png',
    categoryId: '2',
  },
  {
    id: '312',
    krName: '홍시쥬스',
    enName: 'Ripe Persimmon Juice',
    price: 4500,
    desc: '홍시를 그대로 갈아만든 홍시쥬스',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_65a845f42626.png',
    categoryId: '2',
  },
  {
    id: '251',
    krName: '딸기요거트드링크',
    enName: 'Strawberry Yogurt drink',
    price: 4500,
    desc: '딸기를 듬뿍 넣은 딸기 요거트 드링크',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_60516dc2a766.png',
    categoryId: '2',
  },
  {
    id: '379',
    krName: '복숭아요거트드링크',
    enName: 'Peach Yogurt Drink ',
    price: 4800,
    desc: '진짜 복숭아를 과육을 넣어, 진짜 복숭아가 씹히는, 진짜 복숭아가 들어있는 요거트 드링크 (버블스트로우로 드세요~)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fdd8ba7e6d64.png',
    categoryId: '2',
  },
  {
    id: '250',
    krName: '플레인요거트드링크',
    enName: 'Plain Yogurt drink',
    price: 4000,
    desc: '건강한 맛, 건강한 기분의 플레인 요거트 드링크',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2d9281be5946.png',
    categoryId: '2',
  },
  {
    id: '547',
    krName: '플레인요거트 코코스무디',
    enName: 'Plain Yogurt Ccco Smoothie ',
    price: 3900,
    desc: ' 요거트에 우유를 블랜딩 한 새콤한 맛에 코코볼이 토핑 되어 바삭한 식감까지 즐길 수 있는 플레인 요거트 코코스무디 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_9928a99cd086.png',
    categoryId: '3',
  },
  {
    id: '545',
    krName: '망고요거트 코코스무디',
    enName: 'Mango Yogurt Coco Smoothie',
    price: 3900,
    desc: '망고의 부드럽고 달콤한 맛과 상큼한 요거트에 코코볼을 토핑하여 바삭한 식감까지 느낄 수 있는 망고요거트 코코스무디',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_b69d709b36d6.png',
    categoryId: '3',
  },
  {
    id: '548',
    krName: '딸기 코코스무디 ',
    enName: 'Strawberry Coco Smoothie ',
    price: 4400,
    desc: '새콤달콤한 딸기에 진한 우유를 블랜딩 한 부드러운 맛에 코코볼이 토핑되어 바삭한 식감까지 즐길 수 있는 딸기 코코스무디 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_955228e29e6f.png',
    categoryId: '3',
  },
  {
    id: '546',
    krName: '피스타치오 코코스무디',
    enName: 'Pistachio Coco Smoothie',
    price: 4400,
    desc: '피스타치오의 고소한 풍미에 코코볼을 더해 달콤 고소한 피스타치오와 바삭한 코코볼을 함께 즐길 수 있는 피스타치오 코코스무디',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_eb209c5cc5ac.png',
    categoryId: '3',
  },
  {
    id: '495',
    krName: '딸기복숭아스무디',
    enName: 'Strawberry Peach Smoothie',
    price: 4500,
    desc: '새콤 달콤한 딸기와 향긋한 복숭아가 조화를 이룬 스무디 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a07548dac0db.png',
    categoryId: '3',
  },
  {
    id: '148',
    krName: '레몬요거트스무디',
    enName: 'Lemon Yogurt Smoothie',
    price: 4500,
    desc: '새콤 달콤한 레몬과 요거트가 환상의 조화를 이룬 스무디',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_059a6e612b37.png',
    categoryId: '3',
  },
  {
    id: '38',
    krName: '자바칩바나치노',
    enName: 'JavaChip Banaccino',
    price: 5000,
    desc: '달콤한 초콜릿과 자바칩, 고소한 우유에 얼음을 가득넣어 갈아낸 뒤, 휘핑크림을 풍성하게 올리고 초코칩으로 마무리한 음료',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_dd07c01f41d5.png',
    categoryId: '3',
  },
  {
    id: '39',
    krName: '쿠앤크바나치노',
    enName: 'Cookie & Cream Banaccino',
    price: 5000,
    desc: '고소한 우유와 쿠앤크 쿠키, 수북한 얼음을 함께 갈아낸 뒤, 휘핑크림+쿠앤크 조각으로 마무리한 음료',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_e931361e0b59.png',
    categoryId: '3',
  },
  {
    id: '40',
    krName: '민트초코바나치노',
    enName: 'Mint Chocolate Banaccino',
    price: 5000,
    desc: '민초단 모이세요! 청량&상쾌한 민트와 초콜릿, 우유를 얼음과 함께 시원하게 갈아낸 뒤, 휘핑크림+초코칩으로 마무리한 음료',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_95a7524685c7.png',
    categoryId: '3',
  },
  {
    id: '37',
    krName: '녹차바나치노',
    enName: 'Green Tea Banaccino',
    price: 5000,
    desc: '쌉싸름한 녹차에 고소한 우유를 더한 뒤 달콤함으로 밸런스를 맞추고, 수북한 얼음과 함께 갈아낸 뒤 휘핑크림을 듬뿍 올린 음료',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6adea6949d3b.png',
    categoryId: '3',
  },
  {
    id: '278',
    krName: '딸기스무디',
    enName: 'Strawberry Smoothie',
    price: 4500,
    desc: '새콤달콤 딸기가 고소한 우유를 만났다! 부드러운 딸기 스무디',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ed4fb8081923.png',
    categoryId: '3',
  },
  {
    id: '239',
    krName: '레몬딸기스무디',
    enName: 'Lemon Strawberry Smoothie',
    price: 4500,
    desc: '상큼한 레몬과 달콤한 딸기가 만나 상큼달콤한 레몬딸기스무디가 되었어요.',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_a500008b4fbb.png',
    categoryId: '3',
  },
  {
    id: '469',
    krName: '망고스무디',
    enName: 'Mango Smoothie',
    price: 4500,
    desc: '달콤한 망고를 넣어만든 스무디 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8fe56ebfe9d2.png',
    categoryId: '3',
  },
  {
    id: '293',
    krName: '바닐라쉐이크',
    enName: 'Vanilla Shake',
    price: 5000,
    desc: '마다가스카르산 바닐라빈을 넣어 만든 부드럽고 달콤한 바닐라쉐이크',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_89e794699475.png',
    categoryId: '3',
  },
  {
    id: '294',
    krName: '초코쉐이크',
    enName: 'Choco shake',
    price: 5000,
    desc: '진한 초콜릿맛이 풍부하게 느껴지는 초코 쉐이크',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_0f4de72e3327.png',
    categoryId: '3',
  },
  {
    id: '380',
    krName: '복숭아에이드',
    enName: 'Peach Ade',
    price: 4800,
    desc: '톡톡 터지는 탄산수에 진짜 복숭아 넣어만들어, 진짜 복숭아가 씹히는, 진짜 복숭아 에이드 (버블스트로우로 드세요~)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c182f1def00d.png',
    categoryId: '4',
  },
  {
    id: '34',
    krName: '자몽에이드',
    enName: 'Grapefruit Ade',
    price: 4300,
    desc: '달콤 쌉싸름한 자몽 + 톡톡 터지는 탄산수. 어른의 청량함이란 이런 것이다.',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_dae205b2c09a.png',
    categoryId: '4',
  },
  {
    id: '254',
    krName: '레몬에이드',
    enName: 'Lemon Ade',
    price: 4300,
    desc: '상큼한 레몬 + 톡톡 터지는 탄산수의 조합은 가히 신의 한 수',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7f6a0de222cc.png',
    categoryId: '4',
  },
  {
    id: '33',
    krName: '청포도에이드',
    enName: 'Green Grape Ade',
    price: 4300,
    desc: '싱그러운 청포도가 톡톡 터지는 탄산수와 만났다. 청포도 에이드 한모금에 내 마음도 그린그린~',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_221dbe82ebb9.png',
    categoryId: '4',
  },
  {
    id: '543',
    krName: '얼음동동식혜',
    enName: 'Sikhye(Sweet Rice Punch)',
    price: 3500,
    desc: '우리쌀, 우리 원재료로 만든 정성 가득한 식혜에 얼음을 동동 띄워 더욱 더 시원하게 즐기는 달콤한 식혜',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fefde224a8e3.png',
    categoryId: '4',
  },
  {
    id: '536',
    krName: '딸기아이스티',
    enName: 'Strawberry Iced Tea',
    price: 5000,
    desc: '국내산 딸기 건조 슬라이스가 토핑 된 새콤달콤한 딸기와 실론 홍차가 조화로운 색다른 맛의 아이스티 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_e9c1fc8c7a52.png',
    categoryId: '4',
  },
  {
    id: '412',
    krName: '대추쌍화차',
    enName: 'Jujube Black Herbal Tea',
    price: 4500,
    desc: '진한 쌍화 농축액에 대추를 더한 감기 기운 있을 때 마시기 좋은 건강차  ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d066d06a6593.png',
    categoryId: '4',
  },
  {
    id: '449',
    krName: '배도라지차',
    enName: 'Pear Bellflower Root Tea',
    price: 4500,
    desc: '목에 좋은 국내산 도라지에 달콤한 배&모과채를 넣어 향긋함을 더한 건강차',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1b01eafee35b.png',
    categoryId: '4',
  },
  {
    id: '520',
    krName: '유자애플티',
    enName: 'Citron Apple Tea',
    price: 4500,
    desc: '향긋한 유자청에 사과의 달콤함, 레몬의 상큼함이 블렌딩 된 티가 더해져 지루한 일상에 활기를 주는 과일 허브티 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_22303f1d527a.png',
    categoryId: '4',
  },
  {
    id: '522',
    krName: '생강레몬티',
    enName: 'Ginger Lemon Tea',
    price: 4500,
    desc: '국내산 생강으로 만든 몸을 따뜻하게 워밍업 시켜주는 티에 새콤한 레몬을 가미한 건강한 겨울철 티 음료 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6a9ebdeeecea.png',
    categoryId: '4',
  },
  {
    id: '491',
    krName: '캐모마일리치티',
    enName: 'Chamomile Lychee Tea ',
    price: 4000,
    desc: '향긋한 캐모마일에 새콤달콤한 리치와 사과가 블렌딩된 무카페인 티 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_03b22dd47198.png',
    categoryId: '4',
  },
  {
    id: '490',
    krName: '민트유자페어티',
    enName: 'Mint Yuja Pear Tea',
    price: 4000,
    desc: '상쾌한 페퍼민트에 상큼한 국내산 고흥 유자와 달콤한 국산 배가  블렌딩된 무카페인 티',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_96ba8cf23be3.png',
    categoryId: '4',
  },
  {
    id: '381',
    krName: 'NEW복숭아아이스티',
    enName: 'NEW Peach Iced Tea',
    price: 4000,
    desc: '직접 우려낸 얼그레이 홍차에 진짜 백도 복숭아를 과육을 넣어 만든, 고퀄+짱맛! 진짜 복숭아 아이스티 (버블스트로우로 드세요~)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_552d506c2ef9.png',
    categoryId: '4',
  },
  {
    id: '269',
    krName: '제주청귤티',
    enName: 'Jeju Green Tangerine Tea',
    price: 4000,
    desc: '제주청귤로 만든 새콤달콤 제주청귤티로 비타민C 챙기세요!',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_5bbe045581aa.png',
    categoryId: '4',
  },
  {
    id: '52',
    krName: '레몬티',
    enName: 'Lemon Tea',
    price: 4300,
    desc: '레몬의 상큼한 맛을 살린 비타민C 가득한 과일 티',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d072b69b03bf.png',
    categoryId: '4',
  },
  {
    id: '54',
    krName: '자몽티',
    enName: 'Grapefruit Tea',
    price: 4300,
    desc: '자몽 과일 본연의 달콤 쌉싸름한 맛을 즐길 수 있는 과일티 ',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_fbec2cdf7949.png',
    categoryId: '4',
  },
  {
    id: '218',
    krName: '자몽히비스커스티',
    enName: 'Grapefruit Hibiscus Tea',
    price: 4300,
    desc: '일상에 활력을 주는, 달콤쌉싸름한 자몽청과 상큼한 히비스커스를 블렌딩해 만든 과일허브티 (ICE 제조 약 3분 이상 소요)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_3e15ccb10c2a.png',
    categoryId: '4',
  },
  {
    id: '217',
    krName: '레몬페퍼민트티',
    enName: 'Lemon Peppermint Tea',
    price: 4300,
    desc: '마음을 REFRESH 해주는, 새콤달콤한 레몬청과 상쾌한 페퍼민트를 블렌딩해 만든 과일허브티 (ICE 제조 약 3분 이상 소요)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_3e50b115d8cb.png',
    categoryId: '4',
  },
  {
    id: '28',
    krName: '캐모마일',
    enName: 'Chamomile Tea',
    price: 3300,
    desc: '사과를 가리키는 그리스어를 어원으로 가지고 있다는 캐모마일, 풋풋한 사과향과 은은하고 편안한 꽃향기가 가득한 캐모마일티 (ICE 제조 약 3분 이상 소요)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8cb806e52dad.png',
    categoryId: '4',
  },
  {
    id: '49',
    krName: '히비스커스',
    enName: 'Hibiscus Tea',
    price: 3300,
    desc: '기분 전환이 필요할때, 예쁜 레드컬러와 상큼한 향 & 새콤한 맛이 매력적인 히비스커스티 어떠세요. (ICE 제조 약 3분 이상 소요)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_465508a95b24.png',
    categoryId: '4',
  },
  {
    id: '25',
    krName: '얼그레이',
    enName: 'EarlGrey Tea',
    price: 3300,
    desc: '고급스러운 베르가못 향을 가진 클래식한 홍차 (ICE 제조 약 3분 이상 소요)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d0e510a54056.png',
    categoryId: '4',
  },
  {
    id: '29',
    krName: '페퍼민트',
    enName: 'Peppermint Tea',
    price: 3300,
    desc: '맨톨의 시원하고 청량한 향기가 입안을 개운하고 깔끔하게 만들어주는 페퍼민트티 (ICE 제조 약 3분 이상 소요)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8440f3fe6543.png',
    categoryId: '4',
  },
  {
    id: '525',
    krName: '우유크림카스테라',
    enName: 'Milk Cream Castella',
    price: 4500,
    desc: '부드러운 카스테라에 우유크림이 듬뿍 들어간 든든한 디저트',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_4c4b1ce5e908.png',
    categoryId: '5',
  },
  {
    id: '524',
    krName: '버터베이글',
    enName: 'Butter Bagel',
    price: 3500,
    desc: '고급 버터를 가미해 감칠맛과 풍미를 끌어올린 겉바속촉 통베이글',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6a1f65cffbe4.png',
    categoryId: '5',
  },
  {
    id: '505',
    krName: '플레인베이글',
    enName: 'Plain Bagel',
    price: 2400,
    desc: '천연 발효종으로 만든 쫄깃한 플레인베이글',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_ff26726fcee5.png',
    categoryId: '5',
  },
  {
    id: '506',
    krName: '어니언베이글',
    enName: 'Onion Bagel',
    price: 2400,
    desc: '천연 발효종과 부드러운 식감의 양파로 만든 쫄깃한 어니언베이글',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7ca989ba1374.png',
    categoryId: '5',
  },
  {
    id: '475',
    krName: '커스터드도넛',
    enName: 'Custard donut',
    price: 2400,
    desc: '부드럽고 달콤한 커스터드 필링이 가득 들어있는 도넛',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_18b6eb47a045.png',
    categoryId: '5',
  },
  {
    id: '306',
    krName: '햄치즈잉글리시머핀',
    enName: 'Ham & Cheese English Muffin',
    price: 3700,
    desc: '등심으로 만든 햄 & 고소한 체다치즈, 에그샐러드를 넣어만든 샌드위치/밀:미국,캐나다,슬라이스햄(국산),슬라이스치즈(미국호주),에그포테이토샐러드(감자,계란:국내산)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_5f9f0ccd36c3.png',
    categoryId: '5',
  },
  {
    id: '190',
    krName: '콰트로치즈파니니',
    enName: 'Quatro  Cheese Panini ',
    price: 4400,
    desc: '네가지 치즈와 토마토소스, 슬라이스햄이 조화롭게 이루어진 따뜻한 치즈 파니니/밀-미국,캐나다,바나프레소치즈믹스(미국,뉴질랜드,독일등),햄(돼지고기-국산),양파(국산)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_eaa31f3a1e78.png',
    categoryId: '5',
  },
  {
    id: '263',
    krName: '페퍼로니파니니',
    enName: 'Pepperoni Panini',
    price: 4400,
    desc: '고소한 풍미의 페퍼로니와 세가지 치즈가 조화로운 따뜻한 파니니/밀(미국,캐나다),바나프레소치즈믹스(미국,뉴질랜드,독일등),페퍼로니(돼지고기-국산,외국산(미국,아일랜드등),양파(국산',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_c1f345024919.png',
    categoryId: '5',
  },
  {
    id: '274',
    krName: '핫치킨파니니',
    enName: 'Hot Chicken Panini',
    price: 4400,
    desc: '매콤한 치킨과 갈릭마요소스가 만나 더욱더 풍부한 맛을 느낄 수 있는 따뜻한 치즈 파니니 /(밀:미국,캐나다),바나프레소치즈믹스(-미국,뉴질랜드,독일 등),닭고기(국산),양파(국산)',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_640fd0a4c65e.png',
    categoryId: '5',
  },
  {
    id: '420',
    krName: '클럽샌드위치',
    enName: 'Club Sandwich',
    price: 5000,
    desc: ' 담백한 닭가슴살과 치즈, 신선한 야채가 듬뿍 들어있는 깔끔한 맛의 샌드위치',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_f89237fb0c86.png',
    categoryId: '5',
  },
  {
    id: '423',
    krName: '튜나샌드위치',
    enName: 'Tuna Sandwich',
    price: 5000,
    desc: ' 참치 & 에그샐러드 & 신선야채로 속을 가득 채운  담백하고 고소한 맛의 샌드위치',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_40317e4d875c.png',
    categoryId: '5',
  },
  {
    id: '503',
    krName: '할라피뇨불고기샌드위치',
    enName: 'Jalapeno Bulgogi Sandwich',
    price: 5500,
    desc: '든든한 불고기와 할라피뇨의 매콤함, 특제 마요 소스가 조화를 이룬 퓨전 샌드위치',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_7206d997a423.png',
    categoryId: '5',
  },
  {
    id: '488',
    krName: '에그베이컨샌드위치',
    enName: 'Egg Bacon Sandwich\t',
    price: 5500,
    desc: '부드러운 에그마요와 베이컨이 들어간 단짠조합 샌드위치',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_8d2739ff4a33.png',
    categoryId: '5',
  },
  {
    id: '465',
    krName: '말렌카케이크_호두',
    enName: 'Marlenka Cake(Walnut)',
    price: 6000,
    desc: '쫀득한 케익시트 사이사이 호두&천연 체코 허니크림을 겹겹이 샌딩한 체코 전통 디저트 케이크',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_92ab22d016c8.png',
    categoryId: '5',
  },
  {
    id: '466',
    krName: '말렌카케이크_코코아',
    enName: 'Marlenka Cake(Cocoa)',
    price: 6000,
    desc: '쫀득한 초코케익시트 사이 코코아&부드러운 연유크림을 겹겹이 샌딩한 체코 전통 디저트케이크',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_13db9223b478.png',
    categoryId: '5',
  },
  {
    id: '537',
    krName: '딸기마카롱',
    enName: 'Strawberry Macaron',
    price: 2600,
    desc: '상큼달콤 딸기 크림과 부드러운 우유 크림이 만난 딸기마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1d3bae63dfa0.png',
    categoryId: '5',
  },
  {
    id: '387',
    krName: '아몬드봉봉마카롱',
    enName: 'Almondbonbon Macaron',
    price: 2600,
    desc: '쫀득한 꼬끄에 아몬드크림, 초콜릿 가나슈, 초코칩으로 만든 필링이 듬뿍이 들어간 핸드메이드 마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2dcd14e81422.png',
    categoryId: '5',
  },
  {
    id: '388',
    krName: '쿠키앤크림마카롱',
    enName: 'Cookie and Cream Macaron',
    price: 2600,
    desc: '쫀득한 꼬끄안에 달지않은 쿠키&크림 필링을 듬뿍 넣었어요. 행복해지는 맛!',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_6794c1f2ffe4.png',
    categoryId: '5',
  },
  {
    id: '286',
    krName: '산딸기마카롱',
    enName: 'Raspberry Macaron',
    price: 2600,
    desc: '상큼한 산딸기 크림이 듬뿍 들어간 핑크핑크 마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_2011febbb147.png',
    categoryId: '5',
  },
  {
    id: '288',
    krName: '우유마카롱',
    enName: 'Milk Macaron',
    price: 2600,
    desc: '유크림 함량 100%의 청정 뉴질랜드 우유버터로 만든, 진한 우유맛 마카롱. 당도를 낮춰 많이 달지 않아요~',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_30ab7f864d2d.png',
    categoryId: '5',
  },
  {
    id: '289',
    krName: '초콜릿마카롱',
    enName: 'Chocolate Macaron',
    price: 2600,
    desc: '진한 초콜릿을 직접 녹여만들어 초콜릿 풍미가 제대로! 콕콕 박혀있는 초컬릿 청크를 씹는 재미까지. 초콜릿 마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d99ee635719d.png',
    categoryId: '5',
  },
  {
    id: '353',
    krName: '인절미마카롱',
    enName: 'Injeolmi Macaron',
    price: 2600,
    desc: '고소한 콩가루로 맛을 낸 우유버터 필링 속 쫄깃한 인절미가 쏙 박혀있는 인절미 마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_9ec5a9df35d6.png',
    categoryId: '5',
  },
  {
    id: '285',
    krName: '바닐라마카롱',
    enName: 'Vanilla Macaron',
    price: 2600,
    desc: '천연 바닐라 향을 넣어 만들어 고급스럽고 진한 바닐라 맛이 매력적인 마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_292cab060377.png',
    categoryId: '5',
  },
  {
    id: '411',
    krName: '황치즈마카롱',
    enName: 'Yellow Cheese Macaron',
    price: 2600,
    desc: '진한 치즈의 풍미가 가득 담긴, 예쁜 찐노랑 색의 단짠 마카롱',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_d866dcc42738.png',
    categoryId: '5',
  },
  {
    id: '544',
    krName: '흑임자호두쿠키',
    enName: 'Black sesame Walnut Cookie',
    price: 1800,
    desc: '흑임자와 호두가 듬뿍 들어가 진하고 고소한 풍미가 있는 쿠키',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_1edb9988306b.png',
    categoryId: '5',
  },
  {
    id: '538',
    krName: '크랜베리아몬드쿠키',
    enName: 'Cranberry Amond Cookie',
    price: 1800,
    desc: '크랜베리와 아몬드, 코코넛이 들어간 달콤하고 고소한 쿠키',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/img_31bc1c21c32d.png',
    categoryId: '5',
  },
  {
    id: '213',
    krName: '초코칩쿠키',
    enName: 'Chocochip Cookie',
    price: 1800,
    desc: '진한 다크 브라운 초콜릿 쿠키에 초코칩을 추가해, 초콜릿의 매력을 극대화 시킨 초코칩 쿠키',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/Chocochipcookie.png',
    categoryId: '5',
  },
  {
    id: '212',
    krName: '아메리칸쿠키',
    enName: 'American Cookie',
    price: 1800,
    desc: '큼직큼직한 초콜릿 청크가 박혀있는 정통 아메리칸 쿠키. 바나프레소 시그니처 쿠키',
    imgPath: 'https://www.banapresso.com/from_open_storage?ws=fprocess&file=banapresso/menu/Americancookie.png',
    categoryId: '5',
  },
];
